### ISSUE TITLE
Create Initial Module Layout

### ISSUE THREAD

**Issue by darthvadrismydad** [GoldRushMC/quick-game-framework#1]
We should really modularize the way we write this framework. I was thinking we have the following modules:

Game
- Rules
- Action
- Participants

Arena
- Blueprint
- Boundaries
- Games Supported

Voting - Chat based voting

Any thoughts on this proposed modular solution?

**Comment by lexwebb** [comment]
Yeah that's pretty much what i was thinking. I'll see if i can think of anything else we may need.

**Comment by darthvadrismydad** [comment]
Excellent. This way, we can break it up into simple chunks we can each implement simultaneously, knowing how each piece is supposed to interact with the others.
