### ISSUE TITLE
Finalize Save Manager Design and Implement

### ISSUE THREAD

**Issue by darthvadrismydad** [GoldRushMC/quick-game-framework#14]
- Decide the best approach for the saving mechanism
- Implement the approach decided upon

**Comment by darthvadrismydad** [comment]
I feel like using the combo (Vector, Collection<ItemStack>) might be good. We can use the "Block.getDrops()" method to collect all of the ItemStacks for each block, and then you can do what you want with it.

**Comment by lexwebb** [comment]
Just have getdrops will not give me the block data needed for stair placement as an example

**Comment by darthvadrismydad** [comment]
oh... you need the byte data for that, correct?

**Comment by darthvadrismydad** [comment]
So I was thinking... Why don't we use the Block Metadata for saving? Why an ItemStack?
